### ISSUE TITLE
Tutorial SelectEditor is outdated

### ISSUE THREAD

**Issue by pnowak** [handsontable/docs#43] opened 2019-05-14 09:38 UTC
After rewrite `selectEditor` to ES6 this section `SelectEditor - creating editor from scratch` - https://handsontable.com/docs/7.0.3/tutorial-cell-editor.html - is outdate.
We should update code in this tutorial section.

**Comment by wojciechczerniak** [comment] 2019-05-14 09:50
Duplicate of #27

**Comment by pnowak** [comment] 2019-05-14 09:53
Sorry.

**Closed** 2019-05-14 09:53 UTC
Labels: enhancement
