### ISSUE TITLE
Broken user interactions in 6.2.1

### ISSUE THREAD

**Issue by drazafsky** [handsontable/docs#37] opened 2018-12-13 15:35 UTC
### Description
Clicking on cells or column/row headers does nothing. Users should be able to interact with the spreadsheet the same way they did in 6.2.0.

### Steps to reproduce

1. Go to the 6.2.1 angular examples page at https://handsontable.com/docs/6.2.1/frameworks-wrapper-for-angular-examples.html
2. Try to click or interact with any of the cells/columns/rows in the table.

**Comment by AMBudnik** [comment] 2019-07-16 12:39
Can't reproduce the issue now, as we're using JSFiddle, which does not support Internet Explorer.

**Comment by scarletfog** [comment] 2020-08-11 14:41
Same here @AMBudnik - should we close this?

**Comment by AMBudnik** [comment] 2020-08-12 11:29
Yes @scarletfog that issue had to be related to Internet Explorer as JSFiddle does not support it.
@drazafsky if you experience any difficulties with the documentation please leave a comment.

**Closed by AMBudnik** 2020-08-12 11:29 UTC
Labels: wontfix
